name: DuelsTrial
main: net.rampo.duelstrial.DuelsTrial
version: 0.1
author: Rampo
api-version: 1.19
commands:
  duel:
    description: DuelsTrial command
    usage: /duel <name> [kit]
  stats:
    description: DuelsTrial stats command
    usage: /stats <name>
  accept:
    description: DuelsTrial accept command
    usage: /accept <name>